@startuml
title ECサイト 画面遷移図

[*] --> 商品一覧画面 : URL指定、アクセス 
商品一覧画面 : 商品一覧(商品名、値段、画像)
商品一覧画面 : チェックボックス
商品一覧画面 : 購入ボタン
商品一覧画面 : 検索フォーム(商品名)
商品一覧画面 : 検索フォーム(値段)
商品一覧画面 : 検索ボタン

note left of 商品一覧画面
UC01 商品を一覧表示する
end note

商品一覧画面 --> 購入ボタン押下
note left of 購入ボタン押下
UC02 商品を購入する
end note

' 購入ボタン押下 --> 商品一覧画面 : エラー発生


購入ボタン押下 --> 購入明細画面
購入明細画面 : 購入日時
購入明細画面 : 購入商品一覧
購入明細画面 : 合計金額
購入明細画面 : 戻るボタン

購入明細画面 --> 戻るボタン押下
戻るボタン押下 --> 商品一覧画面

商品一覧画面 --> 検索ボタン押下
検索ボタン押下 --> 商品一覧画面
note left of 検索ボタン押下
UC03 商品を検索して表示する
end note

@enduml