@startuml
title ECサイト 画面遷移図
hide empty description

[*] --> 商品一覧画面 : URL指定、アクセス 
商品一覧画面 : 商品一覧(商品名、値段、画像)
商品一覧画面 : チェックボックス
商品一覧画面 : 購入ボタン
商品一覧画面 : 検索フォーム(商品名)
商品一覧画面 : 検索フォーム(値段)
商品一覧画面 : 検索ボタン
商品一覧画面 : メッセージ領域

note left of 商品一覧画面
UC01
end note

商品一覧画面 --> 購入ボタン押下
note left of 購入ボタン押下
UC02
end note

購入ボタン押下 -right-> 購入明細画面
購入明細画面 : 購入日時
購入明細画面 : 購入商品一覧
購入明細画面 : 合計金額
購入明細画面 : 戻るボタン

購入明細画面 -right-> 戻るボタン押下
戻るボタン押下 --> 商品一覧画面

商品一覧画面 -right-> 検索ボタン押下
検索ボタン押下 -left-> 商品一覧画面
note right of 検索ボタン押下
UC03
end note

商品一覧画面 -left-> 管理者メニューボタン押下
管理者メニューボタン押下 -left-> 管理者メニュー
管理者メニュー : 商品一覧(ID,商品名,カテゴリ,税抜き価格,画像データ)
管理者メニュー : 入力フォーム(商品名,カテゴリ,税抜き価格,画像データ)
管理者メニュー : 登録ボタン
管理者メニュー : メッセージ領域
管理者メニュー -left-> 完了ボタン押下 
完了ボタン押下 --> 商品一覧画面

note left of 管理者メニュー
UC04
end note
@enduml