@startuml

title ECサイト_ユースケース図
:利用者: as user
:管理者: as admin

rectangle ECサイト {

    (商品を一覧表示する) as (showProduct)
    (商品を購入する) as (buyProduct)
    (商品を検索する) as (searchProduct)
    (商品データを登録する) as (createProductData)
    (商品データを変更する) as (updateProductData)
    (商品データを削除する) as (deleteProductData)

    left to right direction
    user --> showProduct
    user --> buyProduct
    user --> searchProduct
    admin --> createProductData
    admin --> updateProductData
    admin --> deleteProductData


    note right of showProduct
    UC01
    end note

    note right of buyProduct
    UC02
    end note

    
    note right of searchProduct
    UC03
    end note

    note right of createProductData
    UC04
    end note

    note right of updateProductData
    UC05
    end note
    
    note right of deleteProductData
    UC06
    end note

}
@enduml